---
title: "Fatal Police Shootings"
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,messages=FALSE,results='hide',warnings=FALSE}
###Data Structure & Summary
options(warn=-1,verbose=FALSE)
library(ggplot2)
library(gridExtra)
library(maps)
library(data.table)
library(lubridate)
library(RColorBrewer)
library(corrplot)

path='C:/Users/02laram26/Desktop/Kaggle/US Shootings'
setwd(path)

filenames<-c('Guardian_2015.csv','Guardian_2016.csv','WP_database.csv')
guard2015.dt<-fread(filenames[1],sep=',')
guard2016.dt<-fread(filenames[2],sep=',')
wp.dt<-fread(filenames[3],sep=',')

##Data Structure & Summary
#summary(guard2015.dt)
#summary(guard2016.dt)
#summary(wp.dt)

```


```{r}
##Data Cleaning & Miscellaneous Functions

clean.Guard2015 <-function(datafile){
    datafile[,age:=ifelse(age=='Unknown',-1,age)] #-1: Unknown
    
    datafile[,uid:=as.numeric(uid)]
    datafile[,age:=as.numeric(age)]
    datafile[,gender:=as.factor(gender)]
    
    datafile[,race:=as.factor(raceethnicity)]
    datafile[,raceethnicity:=NULL]
    
    datafile[,armed:=as.factor(armed)]
    datafile[,day:=as.factor(day)]
    datafile[,state:=as.factor(state)]
    datafile[,classification:=as.factor(classification)]
    
    datafile
}

clean.Guard2016<-function(datafile){
    datafile[,age:=ifelse(age=='Unknown',-1,age)] #-1: Unknown
    datafile[,age:=ifelse(age=='40s',-2,age)] #-1: 'Unknown'40s'

    datafile[,uid:=as.numeric(uid)]
    datafile[,age:=as.numeric(age)]
    datafile[,gender:=as.factor(gender)]

    datafile[,race:=as.factor(raceethnicity)]
    datafile[,raceethnicity:=NULL]
    
    datafile[,armed:=as.factor(armed)]
    datafile[,day:=as.factor(day)]
    datafile[,state:=as.factor(state)]
    datafile[,classification:=as.factor(classification)]
    
    datafile
}

clean.wp<-function(datafile){
    datafile[,date:=ymd(date)]
    datafile[,manner_of_death:=as.factor(manner_of_death)]
    datafile[,armed:=as.factor(armed)]
    datafile[,gender:=as.factor(gender)]
    datafile[,race:=as.factor(race)]
    datafile[,signs_of_mental_illness:=as.factor(signs_of_mental_illness)]
    datafile[,threat_level:=as.factor(threat_level)]
    datafile[,flee:=as.factor(flee)]
    datafile[,body_camera:=as.factor(body_camera)]
    datafile[,state:=as.factor(state)]
   
    datafile[,age:=ifelse(is.na(age),-3,age)]
    
    datafile[,year:=day(date)] 
    datafile[,month:=month(date,label=TRUE,abbr=FALSE)]
    datafile[,year:=year(date)]
    
    datafile
}
```

###Custom Analysis Functions
```{r}
tbl.ECDF<-function(datatable){
    ECDF<-vector(mode='numeric',length = length(datatable))
    
    for (i in 1:nrow(datatable)) {
       ECDF[i]<-sum(datatable[nrow(wp.tbl_armed):(nrow(wp.tbl_armed)-(i-1))])    
    }
    
    ECDF<-ECDF/sum(datatable)
}
```

```{r,include=FALSE}
#Create Single data table for each source
clean.guard.dt<-rbindlist(
                    list(
                        clean.Guard2015(guard2015.dt),
                        clean.Guard2016(guard2016.dt)
                        ),
                    use.names=TRUE
                    )
    clean.guard.dt[,year:=as.factor(year)]

clean.wp.dt<-clean.wp(wp.dt)
    clean.wp.dt[,year:=as.factor(year)]


```

###Exploratory Data Analysis

*Victim Descriptors*            | *Officer Descriptors* | *Situation Descriptors*
------------                    | -------------         | ------------- 
Name(G & WP)                    | Body Camera           | Date(G & WP)
Age(G & WP)                     | -------------         | Location (G & WP)
Race(G & WP)                    | -------------         | Signs of Mental Illness (WP)
Gender(G & WP)                  | -------------         | Armed(G & WP)
Signs of Mental Illness (WP)    | -------------         | Classification/Manner of Death (G & WP)
-------------                   | -------------         | Threat Level (WP)
-------------                   | -------------         | Flee (WP)
-------------                   | -------------         | Law Enforcement Agency(G)

####Guardian Data
```{r,fig.height=10,fig.width=30}
##Victim

    #Age Distribution
    g.guard.age<-ggplot(data = clean.guard.dt[age>=0],aes(x=age,fill=year))+
        geom_histogram(position='identity',alpha=0.5,binwidth = 5)+
        xlab('Victim Age')+ylab('Fatalities')+theme(text = element_text(size = 12))+
        annotate("text", x = 70, y = 100, 
                 label = paste('Median Age = ',median(clean.guard.dt[age>=0]$age)))
    
    #Race Distribution
    g.guard.race<-ggplot(data=clean.guard.dt, aes(x=reorder(race, table(race)[race]))) + 
        geom_bar(fill='red')+
        xlab('Race')+ylab('Total Fatalities 2015-2016')+
        theme(text = element_text(size = 15))+
        coord_flip()
    
    grid.arrange(g.guard.age,g.guard.race,ncol=2)

##Situation
    
    #Location (States)
    g.guard.state<-ggplot(data=clean.guard.dt, 
                          aes(x=reorder(state, table(state)[state]))) + 
        geom_bar(fill='red')+coord_flip()+
        xlab('State')+ylab('Fatalities')+
        theme(text = element_text(size = 15))
    
    #Armed
    g.guard.armed<-ggplot(data=clean.guard.dt, 
                          aes(x=reorder(armed, table(armed)[armed]),fill=race)) + 
        geom_bar()+ scale_fill_brewer(palette = 'BrBG')+
        coord_flip()+
        xlab('Type of Weapon')+ylab('Fatalities')+
        theme(text = element_text(size = 15))
    
    #Cause of Death
    g.guard.COD<-ggplot(data=clean.guard.dt, 
                          aes(x=reorder(classification, 
                                        table(classification)[classification]))) + 
        geom_bar(fill='red')+coord_flip()+
        xlab('Cause of Death')+ylab('Fatalities')+
        theme(text = element_text(size = 15))
    
    grid.arrange(g.guard.state,g.guard.COD,g.guard.armed,ncol=3)


```


####Washington Post Data
```{r,fig.height=10,fig.width=30}
##Victim

    #Victim Age Distribution each Year
    g.wp.age<-ggplot(data = clean.wp.dt[age>=0],aes(x=age,fill=year))+
        geom_histogram(position='identity',alpha=0.5,binwidth = 5)+
        xlab('Age')+ylab('Fatalities')+
        theme(text = element_text(size = 15))+
        annotate("text", x = 70, y = 75, 
                 label = paste('Median Age = ',median(clean.wp.dt[age>=0]$age)))
    
    #Police Killings by Race
    g.wp.race<- ggplot(data=clean.wp.dt, aes(x=reorder(race,table(race)[race])))+
        geom_bar()+ scale_fill_brewer(palette = 'BrBG')+
        xlab('Race')+ylab('Fatalities 2015-2016')+
        theme(text = element_text(size = 15))+
        coord_flip()

    grid.arrange(g.wp.age,g.wp.race,ncol=3)

##Situation

    #Location (States)
    g.wp.state<-ggplot(data=clean.wp.dt, aes(x=reorder(state, table(state)[state]))) + 
        geom_bar(fill='red')+coord_flip()+
        xlab('State')+ylab('Fatalities')+
        theme(text = element_text(size = 15))
    
    #Armed
    g.wp.armed<-ggplot(data=clean.wp.dt, aes(x=reorder(armed, table(armed)[armed]),fill=race)) + 
        geom_bar()+ scale_fill_brewer(palette = 'BrBG')+
        coord_flip()+
        xlab('Type of Weapon')+ylab('Fatalities')+
        theme(text = element_text(size = 15))
    
    
    clean.wp.dt[,.N,by=manner_of_death]
    
```



```{r,eval=FALSE}    
#Top 95% of Weapons in Possession of Killed Citizen
wp.tbl.armed<- table(clean.wp.dt$armed)
    wp.tbl.armed<-wp.tbl_armed[order(wp.tbl.armed)]
    wp.top10.armed<-tail(wp.tbl.armed,n=12)
    
    wp.armed.ECDF<-tbl.ECDF(wp.tbl.armed) #ECDF of WP weapons
    
    print(
      paste(
              'Washington Post: Top 10 Types of Weapons Account for' ,
                    as.character(sum(wp.top10.armed)/sum(wp.tbl.armed)*100) ,
                    '% of National Occurrences'
            ),sep = ''
      )

  
guard.tbl_armed<- table(clean.guard.dt$armed)
    guard.tbl.armed<-guard.tbl_armed[order(guard.tbl.armed)]
    guard.top10.armed<-tail(guard.tbl.armed,n=6)
    
    print(
      paste(
              'The Guardian: Top 10 Types of Weapons Account for' ,
                    as.character(sum(guard.top10.armed)/sum(guard.tbl.armed)*100) ,
                    '% of National Occurrences'
            ),sep = ''
      )
  

#States with Most Police Shootings - May be useful to Calculate ECDF for G & WP
wp.tbl.state<-table(clean.wp.dt$state)
      wp.tbl.state<-wp.tbl.state[order(wp.tbl.state)]
      N=10
      wp.top.states<-tail(wp.tbl.state,n=N)
    
      print(paste('Median 2015-2016 State Deaths by Police Shootings is ',
                  median(wp.tbl.state) ))
    
      print(
       paste(
              'Washington Post:', as.character(N), 'States with the Most Police Shootings Account for' ,
                    as.character(sum(wp.top.states)/sum(wp.tbl.state)*100) ,
                    '% of National Police Shooting Fatalities'
            ),sep = ''
      )

guard.tbl.state<-table(clean.guard.dt[classification=='Gunshot']$state)
      guard.tbl.state<-guard.tbl.state[order(guard.tbl.state)]
      N=10
      guard.top.states<-tail(guard.tbl.state,n=N)
    
      print(paste('Median 2015-2016 State Deaths by Police Shootings is ',
                  median(guard.tbl.state) ))
    
      print(
       paste(
              'Guardian:', as.character(N), 'States with the Most Police Shootings Account for' ,
                    as.character(sum(guard.top.states)/sum(guard.tbl.state)*100) ,
                    '% of Police Shooting Fatalities'
            ),sep = ''
      )

```

#Interaction of Guardian Data

**Variables of Interest:** Age, Month, Type of Weapon, & Race

```{r,fig.height=10,fig.width=15}

cond.target<-function(field, target){
    #(target-target%%5)/5 + 1
    
    age.levels <- as.character(c(1:17))
    
    month.levels <- c(" 'January' " ," 'February' ", " 'March' "," 'April' "," 'May' ", " 'June' ", " 'July' ",
                        " 'August' "," 'September' ", " 'October' ", " 'November' ", " 'December' ")
    
    armed.levels<-c( " 'Disputed' " ," 'Firearm' "," 'Knife' "," 'No' ",
                     " 'Non-lethal firearm' "," 'Other' "," 'Unknown' "," 'Vehicle' ")           

    race.levels<-c(" 'Arab-American' "," 'Asian/Pacific Islander' ", " 'Black' "," 'Hispanic/Latino' ",       
                    " 'Native American' "," 'Other' "," 'Unknown' "," 'White' " )
    
    v.str <- ifelse(field==1,'((age - age%%5)/5)',
                  ifelse(field==2,'month',
                         ifelse(field==3,'armed','race')))
    
    trgt.str<-ifelse(field==1,age.levels[target],
                  ifelse(field==2,month.levels[target],
                         ifelse(field==3,armed.levels[target],race.levels[target])))
    
    paste0(v.str,'==',trgt.str)
} #Creates Conditional Indexing String


#v('gunshot' & 'male') = [ [age], [month] ,[armed], [race] ]
#age.levels <- as.character(c(1:17))
age.levels <- c('Age:5-10','Age:11-15','Age:16-20',
                'Age:21-25','Age:26-30','Age:31-35','Age:36-40',
                'Age:41-45','Age:46-50','Age:51-55','Age:56-60',
                'Age:61-65','Age:66-70','Age:71-75','Age:76-80',
                'Age:81-85','Age:86-90')

month.levels <- c( 'Month:January'  , 'Month:February' ,  'Month:March' , 'Month:April' , 'Month:May' , 
                   'Month:June' ,  'Month:July' ,  'Month:August' , 'Month:September' , 
                   'Month:October' ,  'Month:November' , 'Month:December' )

armed.levels<-c(  'Armed:Disputed'  , 'Armed:Firearm' , 'Armed:Knife' , 'Armed:No' ,
                  'Armed:Non-lethal firearm' , 'Armed:Other' , 'Armed:Unknown' , 'Armed:Vehicle' )           

race.levels<-c( 'Race:Arab-American' , 'Race:Asian/Pacific Islander' ,  'Race:Black' ,
                'Race:Hispanic/Latino' ,  'Race:Native American' ,
                'Race:Other' , 'Race:Unknown' , 'Race:White'  )

pred.names<-c(age.levels,month.levels,armed.levels,race.levels)

age.bins.N <-length(age.levels)
month.N <- length(month.levels)
armed.N <- length(armed.levels)
race.N<-length(race.levels)
total.levels<-age.bins.N+month.N+armed.N+race.N

mat.heat<-matrix(nrow=total.levels,ncol=total.levels)

for (i in 1:total.levels) {
    cond1.field<-ifelse(i<age.bins.N+1,1,
                    ifelse(i<age.bins.N+month.N+1,2,
                        ifelse(i<age.bins.N+month.N+armed.N+1,3,4)))
    
    cond1.target<-ifelse(i<age.bins.N+1,i,
                    ifelse(i<age.bins.N+month.N+1,i-age.bins.N,
                        ifelse(i<age.bins.N+month.N+armed.N+1,i-age.bins.N-month.N,
                                        i-age.bins.N-month.N-armed.N)))
    
    for (j in 1:total.levels) {
        cond2.field<-ifelse(j<age.bins.N+1,1,
                        ifelse(j<age.bins.N+month.N+1,2,
                            ifelse(j<age.bins.N+month.N+armed.N+1,3,4)))
            
        cond2.target<-ifelse(j<age.bins.N+1,j,
                    ifelse(j<age.bins.N+month.N+1,j-age.bins.N,
                        ifelse(j<age.bins.N+month.N+armed.N+1,j-age.bins.N-month.N,
                                        j-age.bins.N-month.N-armed.N)))
        
        cond1 <- parse(text=cond.target(cond1.field,cond1.target))
        cond2 <- parse(text=cond.target(cond2.field,cond2.target))
        
        if(j==i){#Artificially Zero Correlation with Self
            mat.heat[j,i]=0
            next
        }
        
        mat.heat[j,i]<- nrow(clean.guard.dt[((age>=0) & gender=='Male' & classification =='Gunshot' & 
                                                 eval(cond1) & eval(cond2))])   
    }    
}

heatmap(mat.heat+1,labCol=pred.names,labRow = pred.names,
        Rowv = NULL,Colv = NA,scale = 'column', 
        main='Male Gunshot Fatalities: Factor Interactions',
        margins=c(9,9),cexRow = 1.25,cexCol = 1.25)
```

```{r,results=FALSE}
top50.vals<-tail(sort(mat.heat),n=100)
top50.vals<-top50.vals[seq(from=1,to=length(top50.vals),by=2)]

top.cond<-matrix(nrow=1,ncol=3)
for (i in 1:length(top50.vals)) {
    top.cond<- rbind(top.cond, c(which(mat.heat==top50.vals[i],arr.ind = TRUE)[1,],top50.vals[i]))
}

top.cond<-top.cond[2:nrow(top.cond),]
top.cond.dt<-data.table(top.cond)
setnames(top.cond.dt,c('C1','C2','Occurrences'))

top.cond.dt[,Condition1:=pred.names[C1]]
top.cond.dt[,Condition2:=pred.names[C2]]
setorderv(top.cond.dt,'Occurrences',-1)


print(head(top.cond.dt,n=20))

```

